name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Create build directory
      run: mkdir ./build
    - name: prepare build
      run: cd build; cmake ..
